name: getx_near
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  get: ^4.7.3
  flutter_config: ^2.0.2
  google_maps_flutter: ^2.14.0
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  sliding_up_panel: ^2.0.0
  sizer: ^2.0.15
  flutter_spinkit: ^5.2.2
  auto_size_text_field: ^2.2.4
  shared_preferences: ^2.5.4
  auto_size_text: ^3.0.0
  liquid_progress_indicator_v2: ^0.5.0
  socket_io_client: ^3.1.4
  intl: any
  # device_preview: ^1.1.0
  flutter_slidable: ^4.0.3
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  flutter_neumorphic:
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor
  showcaseview: ^5.0.1
  flutter_cache_manager: ^3.4.1
  just_audio: ^0.10.5
  safe_device: ^1.3.8
  wechat_assets_picker: ^10.1.0
  mime: ^2.0.0
  map_launcher: ^4.4.2
  flutter_svg: ^2.2.3
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  visibility_detector: ^0.4.0+2
  flutter_localizations:
    sdk: flutter
  pin_code_fields: ^8.0.1
  flutter_markdown: ^0.7.7
  flutter_sliding_tutorial: ^2.1.0
  lottie: ^3.3.2
  flutter_app_badger: ^1.5.0
  connectivity_plus: ^7.0.0
  webview_flutter: ^4.13.1
  flutter_lints: ^6.0.0
  photo_manager: ^3.8.3

# dependency_overrides:

# 現在google_mapとimage_pickerの併用は不可(ロゼッタ使用している為) m1sim
# multiple_image_picker を使用
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/sounds/
    - assets/lotties/
    - assets/markdown/
    - .env
    - pubspec.yaml

flutter_icons:
  image_path: 'assets/icon/icon-ios.png'
  image_path_ios: 'assets/icon/icon-ios.png'
  android: true
  ios: true
  adaptive_icon_foreground: 'assets/icon/icon-android.png'
  adaptive_icon_background: '#ffccd6'

flutter_native_splash:
  image: 'assets/icon/splash-icon.png'
  color: '#ffccd6'
  fullscreen: true
  android_12:
    icon_background_color: '#ffccd6'
    image: 'assets/icon/splash-icon.png'
